var questionAnswers = [
    ['Watashi wa Nihon-jin desu', 'I am Japanese'],
    ['Kore wa desu ka', 'What is this?'],
    ['Dewa/Ja mata', 'Well then...'],
    ['Itterasshai', 'So long (said to someone leaving)'],
    ['Ittekimasu', 'So long (said by the one that is leaving)'],
    ['Gochisosamadeshita', 'Said after eating meal'],
    ['Omedeto gozaimasu', 'Congratulations'], 
    ['Do itashimashite', 'You are welcome'],
    ['Mo ichi-do onegaishimasu', 'Once again please'],
    ['Dozo o-sakini', 'Please, go ahead'],
    ['Ki o tsukete', 'Take care, be careful'], 
    ['O-daijini', 'Take care (said to someone ill or injured)'], 
    ['Kochira wa Tama-san desu', 'This is Tama'], 
    ['Sumisu-san wa ABC Fuzu no bengoshi desu', 'Smith is a lawyer for ABC Fuzu'], 
    ['Buruan-san wa gakusei desu', 'Brown is a student'],
    ['Richard-san wa Igirisu-jin desu ka, Amerika-jin desu ka', 'Is Richard from England or America?'],
    ['Hajimemashite. Toyota no Tama desu. Yoroshiku onegaishimasu', 'I am Tama working at Toyota. Nice to meet you'], 
    ['Kochira wa Berurin Motazu no Hofuman-desu', 'This is Hoffman working at Berlin Motors'],
    ['Daigaku', 'University'], 
    ['Ginko', 'Bank'],
    ['Anata', 'You'],
    ['Dare', 'Who'], 
    ['Watashi no meishi desu', 'This is my business card'],
    ['Kore wa Tama-san no namae desu ka', 'Is this your (Tama) name?'], 
    ['Kaishi', 'Company/office'], 
    ['denwa-bango', 'telephone number'], 
    ['denwa', 'telephone'], 
    ['bango', 'number'], 
    ['jusho', 'address'], 
    ['meru-adoresu', 'mail-address'], 
    ['zero-shichi-kyu', 'zero-seven-nine']
]